### ISSUE TITLE
Tips om kontakter

### ISSUE THREAD

**Issue by SnapplezOsev** [Scouterna/Google-Scoutnet-synk#16]
Ett tips på att göra så att kåren får in alla medlemmar från scoutnet som kontakter i G-suite i en katalog så man kan skicka till enskilda scouter vid tillfälle. Just detta har min kår ett behov av.

**Comment by los7702** [comment]
Jag tittar på just detta men jag har lite svårt att se hur man kan använda det i verksamheten 
Jag skulle själv vilja ha in de yngre barnen med anhöriga som epostadresser. Det hade varit bra om man i mobilen kunde se information om avdelning på en kontakt när man skall skicka e-post
Jag kan fixa in dem men det bör vara användbart. 
Jag tänker att man gör det via inställningarna och väljer att det skall vara kontakt istället för konto. Återkom med tankar....

**Comment by los7702** [comment]
Detta är fortfarande aktuellt och jag försöker bara förstå hur jag skall göra anropen.

**Comment by webbmastern** [comment]
@SnapplezOsev  Skulle du kunna förklara behovet lite mer med exempel? T.ex varför det inte är tillräckligt att kunna kolla upp det i Scoutnet?

Om detta skulle implementeras skulle det enbart vara tillgängligt via ens google-konto hos kåren och inte ens privata då det inte bör gå att synkronisera kontakter dit.

**Comment by webbmastern** [comment]
Jag håller på att arbeta med kontaktsynkronisering nu för att skapa etiketter som kontakterna samlas under. Tänk som en kontaktgrupp.
För att det ska fungerar att skicka e-brev till dessa kontaktgrupper lagras enbart en e-postadress per kontakt och alltså ingen enskild kontakt per medlem eller flera e-postadresser mm per medlem.
Tanken är alltså att det är en kontaktgrupp som ska användas för e-postdistribution och inte som en kontaktbok.

Jag har haft synsättet att utgå från Google-grupper som redan är skapade för att minska komplexiteten samt anropen till Scoutnet.
Det är enbart e-postadresser som synkroniseras.
Tanken är att det ska fungera med privat gmail också genom att varje användare kör en egen instans av App Script som anropar kårens egna uppsatta instans.

**Comment by los7702** [comment]
@webbmastern  Problemet kan bli att man blir tvungen att exponera apinycklar till personer som inte skall ha all information.
Det jag skulle vilja lyckas med är att när jag är på hajk och en scout kommer till mig så vill jag kunna ta fram min telefon, leta upp scouten i min telefon och ringa någon av hens vårdnadshavare. eller alternativt skicka ett mail.
tyvärr har jag inte prioriterat att ta reda på hur man authentiserar till apiet som hantera external contacts än för jag trodde att det vid detta laget skulle ha implementerats i de nya apierna som byggs upp.

En workshop i frågan ? där vi kan hjälpas åt i samma projekt istället för att sitta på olika öar och hitta på själva?
Mvh Lasse

**Comment by webbmastern** [comment]
Hej,
Det upplägget som jag arbetar med nu är att kåren sätter upp en egen instans av skript där api-nycklar mm är definerade och att varje användare sätter upp en egen instans av ett skript som då ska anropa kårens instans. Tänk som en BFF backend for frontend. API-nycklarna ska då inte vara tillgängliga/synliga för vanliga ledare i kåren.
Varje enskild användare som vill synkronisera ska då ange en kombination av e-postadress/lösenord för att autentisera användaren. Dessa e-postadresser skulle då behöva skapas av kårens admin, men min tanke är att det skulle kunna gå att få dem automatiskt skapade genom koppling till körning av skriptet för Medlemslistor.

Jag har arbetat efter att synkronisera efter data i Google grupper för att automatiskt kunna detektera vilka kontaktlistor som en användare är medlem i och får skicka till samt för att inte än en gång behöva ställa in ev komplicerade inställningar för vilka som ska ingå som gjordes för grupper. Den stora nackdelen är att inte kontaktinformation som inte är e-post inte följer med då det ej sparas i Google Grupper.
En annan lösning skulle kunna vara att ha en tabell med en kolumn för en Google-grupp och den andra med Scoutnet list-id där den första definierar vilka som ska få skapa en kontaktlista och de övriga vilka kontakter som ska ingå.

@los7702 Släng gärna iväg ett mejl till mig för vidare diskussion så kan vi ta en sittning och diskutera lösningar.
