### ISSUE TITLE
Länk till gruppen fungerar ej

### ISSUE THREAD

**Issue by fredrikbaberg** [Scouterna/Google-Scoutnet-synk#17]
När synk körs så skapas en länk i kalkylarket, åtminstone första gången det körs för en grupp. Tas den länken bort ersätts den inte.

Skapar jag en ny grupp stämmer inte länken som skapas, den hamnar i gruppens "inkorg" istället för sida med lista över medlemmar.

**Comment by fredrikbaberg** [comment]
Jag har för mig att det tidigare varit en annan adress, men nu har jag i mitt dokument ändrat till: `=HYPERLÄNK("https://admin.google.com/ac/groups/"&J3&"/members";"Länk")` (För rad 3).

**Comment by fredrikbaberg** [comment]
Alternativt (efter att ha testat lite) det antagligen lite snyggare: `https://groups.google.com/a/<domain>/forum/#!members/<list_name>`.

**Comment by webbmastern** [comment]
e91fb1d Länk till grupp skapas på nytt om den tas bort
38ca834 Länk till en grupp har en ny url till den nya vyn för Grupper som tydligt visar vilka som får skicka / ta emot från listan.
