### ISSUE TITLE
Lösenordsåterställning ej populerat.

### ISSUE THREAD

**Issue by los7702** [Scouterna/Google-Scoutnet-synk#21]
vi har idag ca 50 vuxna i vår kår.
Nu när Corona dök upp så påskyndades vår implementering av Google plattformen. 
Synkningen går bra som det är men jag saknade återställningsinformation på konton när jag började synca konton. 

Som scriptet ser ut så uppdateras Googleanvändaren utifrån information från objektet som gommer från maillistan som är angiven userAccountConfig, det innebär att det finns en begränsad mängd data att anväda som källa till uppdateringen. tillexempel så saknas mobilnummer.

Jag har för att kunna uppdatera den informationen på Googlekontot gjort lite ändringar i Användare.gs som innebär att när listorna gås igenom så letar jag upp medlemen i arrayen allmembers och skickar den till funktionerna som skall göra jobbet. 

samt att  jag använder lite linq/lambda syntax istället för en mängd "for" satser, jag tror att det är lite lättare att följa koden då

Vill ni att jag öppnar  en pullrequest för att implementera detta i projektet? och eller delar av det. 

Jag har aldrig vare sig programmerat mot Googles plattform eller bidragit med kod i Github tidigare. 

Jag har alltid varit en ensamvarg i mina projekt

MVH
Lasse Skogshus

**Comment by webbmastern** [comment]
Hej Lasse,
Kan du utveckla lite mer gällande avsaknaden av återställningsinformation. Jag hängde inte med :)

Ang att få in telefonnummer låter intressant. För närvarande är det bara namn och medlemsnummer som du sett.

Ang syntaxen. Om det verkar lättare att följa koden så låter det ju bra.

Du får gärna öppna pullrequest. Helst en för syntaxen och en för användarfält om det inte blir extra jobb.

Mvh
Emil Öhman

**Comment by los7702** [comment]
Klart att vi fixar en sak i taget....
Jag skall bara försöka få till det.... :-) ge mig denna och kanske nästa...
Jag utvecklar återställningsinformationen i den pullen. 
JAg är helt ny på detta med Git så Säg till mig om något blir knas
