### ISSUE TITLE
Mobilnummer

### ISSUE THREAD

**Issue by carlbjelksjo** [Scouterna/Google-Scoutnet-synk#25]
Ett förslag: kan vi synka in G Suiteanvändarnas mobilnummer till deras profiler?
Det skulle göra t ex katalogen mycket användbar.

**Comment by los7702** [comment]
Jag kan fixa detta vecka 31. Men frågan är om man inte skall ha set som en inställning (valmöhlighet) då numrera blir tillgängliga för alla.

**Comment by kallemooo** [comment]
Jag har för mig att mobilnumret är publik info i scoutnet. Dvs loggar du in i scoutnet så kan du se mobilnumret på andra ledare i scoutkåren (publikt innom en scoutkår).

Office365 synkningen har med mobilnumret i synkning av användarprofiler.
