### ISSUE TITLE
E-postadresser och grupper

### ISSUE THREAD

**Issue by carlbjelksjo** [Scouterna/Google-Scoutnet-synk#26]
Nu går det att styra på varje enskild e-postlista i Scoutnet vilka e-postadresser som den sänder till.
Detta påverkar även API:t går det att styra om så att detta även följer med till G suitegrupperna?

Exempel på användning: du har en avdelning med yngre ledare (utmanare) som även har kontaktuppgifter till sina anhöriga i Scoutnet.
Du vill genom att kombinera två e-postlistor från Scoutnet skapa en lista för en avdelning där scouternas alla kontaktuppgifter följer med men i ledarnas fall så blir det bara den primära e-postadressen.

**Comment by TobbeEdgeware** [comment]
Jag tycker att det verkar fungera genom att göra 3 grupper i Google Dokumentet som definierar mailistorna

1. ledare (med -m)
2. föräldrar (alla på avdelningen + en negativ regel som tar bort ledarna) (med -mf)
3. ledare + föräldrar definierade i Google Docs som mailadresserna till de 2 grupperna

![Screenshot 2020-09-13 at 10 36 33](https://user-images.githubusercontent.com/16939725/93013989-67551d00-f5ad-11ea-9dfc-8b27f249e867.png)

**Comment by webbmastern** [comment]
Hej,
Inställningen i Scoutnet påverkar synkinställningen endast om **e** används då det använder attributet **extra_emails** som hämtas från Scoutnets API.
För användning av detta skript rekommenderas att välja **Primär e-post + kopior enligt medlemsprofil** för att **e** ska kunna komma till nytta och endast skicka till de e-postadresser som medlemmen själv väljer (+primär e-postadress).
Eventuell inställning av till vilka attribut som ska anges som mottagare görs förslagsvis i Google kalkylarket.
