### ISSUE TITLE
Två ändringsförslag i gruppinställningarna

### ISSUE THREAD

**Issue by carlbjelksjo** [Scouterna/Google-Scoutnet-synk#27]
Förslag:
Gör det möjligt att stänga av konversationshistoriken i grupperna.

Samt att på gruppnivå ställa in vilken e-postadress som modererar skräpposten.

**Comment by los7702** [comment]
Jag läste i någon issue att det kanske blev för invecklat med många alternativ. Men jag håller med. Det som går att exponera är bra. 
Jag är på semester nu men tittar och funderar när jag är tillbaka.
