### ISSUE TITLE
API-anrop till groupsSettings.groups.patch misslyckades med felet, fel typ på booleans

### ISSUE THREAD

**Issue by hakankvist** [Scouterna/Google-Scoutnet-synk#28]
Jag har fått följande fel de senaste två dagarna (kör inte den senaste versionen).

GoogleJsonResponseException: API-anrop till groupsSettings.groups.patch misslyckades med felet:
Invalid value at 'group_settings.include_custom_footer' (TYPE_STRING), true
Invalid value at 'group_settings.allow_external_members' (TYPE_STRING), true
Invalid value at 'group_settings.include_in_global_address_list' (TYPE_STRING), true
    at changeGroupPermissions(Grupper:915:30)
    at updateGroup(Grupper:601:3)
    at Grupper(Grupper:187:7)

Jag tolkar det som att dessa tre parametrar förväntas vara av typen STRING.
Dessa värden sätts som booleans (true, false) och inte ("true", "false") i koden.

Jag har försökt söka i googles dokumentation men blir inte klok på om parametrarna ska anges som booleans eller strängar.

Jag testat att ändra till strängar, och då får jag inte detta felet längre.

**Comment by hakankvist** [comment]
Det är funktionen changeGroupPermissions som fallerar.

**Comment by hakankvist** [comment]
Verkar vara fixat i https://github.com/Scouterna/Google-Scoutnet-synk/commit/e95cc8910a4cc8da4057ca090651f000bdf63abb så vi kan stänga den här issuen.

**Comment by webbmastern** [comment]
Ah. Det var lite konstigt att API:t inte hade klagat innan på det.
