### ISSUE TITLE
Saknar grundläggande information om hur systemet fungerar och hur man får tag i listid, rule_id etc

### ISSUE THREAD

**Issue by TobbeEdgeware** [Scouterna/Google-Scoutnet-synk#30]
Det här verkar vara ett användbart system och jag försöker sätta upp det. Tack för ett stort jobb!

Men, det har varit svårt för mig att förstå principerna och hur man får tag på listid, rule_id etc från Scoutnet, så jag skulle vilja ha mer dokumentation, om grundläggande kopplingar,  var man får listid, rule_id etc ifrån och hur man gör när man
redan har manuellt kontrollerade listor och grupper tidigare.

Jag tror att ett bra sätt att få till detta vore att skriva några ämnen i Wiki'n här för det här projektet.

Här är några frågor/områden som jag skulle vilja ha mer info om:

1. Gruniden:  Man gör fullt fungerande maillistor i Scoutnet men de används bara som mallar. Det är lite udda och kan kanske förklaras tydligare varför man valt göra på detta sätt och vad det betyder. Men sen också
    * Vilka av inställingarna i listan spelar någon roll? namn, beskrivning, fördefinierad/privat, öppen för inkommande epost E-postmottagare? Spelar det någon roll om e-postlistan är aktiv?
2. Varje lista har ett id. Jag kan inte se någon beskrivning hur man får tag i dessa. Emil tipsade om "Webbkoppling > API-nycklar och endpoints" så jag hittade till slut, men innan dess laddade jag ner json-blobar och kollade.
3. Det skapas användare automatiskt, men de har ingen sekundär emailadress såvitt jag kan se och får inget mail om att de har ett nytt konto. Alltså måste man väl göra en manuell process och kontakta dessa personer och tala om för dem att de har ett konto och ge dem ett lösenord? Kanske självklart, men vore ändå bra att peka ut.
4. Använda tidigare registrerade användare. Jag har fått lite information per mail från Emil, men vore bra att ha en Wiki-artikel om att man ska gå in och sätta Scoutnet medlemsnummer till anställningsnummer och flytta användarna till Scoutnet organisationen, för att undvika att få en dubblett.
5. Sen saknar jag också information om hur man går över från en befintligt maillista till en genererad utan att behöva radera den gamla. Skall gå enligt Emil, men kanske vore bra att dokumentera möjligheten åtminstone, om det är svårt att förklara i närmare detalj.

Jag har till slut tagit mig rätt långt, så det går ju uppenbarligen, men lite mer information hade sparat mig en hel del tid. När jag väl lärt mig lite mer själv kan jag kanske bidra med en Wiki-artikel om det finns intresse.

**Comment by los7702** [comment]
Hej Tobbe.... Jag tar gärna en session via Google meet och svarar/diskuterar alla dina frågor så får du kött på benen och kan bidra med wiki sedan .... på så sätt kan både du och jag bidra till projektet... :-)
Skicka mig ett PM så kan vi söka upp varandra... mvh Lasse

**Comment by flindeberg** [comment]
Slog ni era kloka huvuden ihop och gjorde något ut detta? @los7702 @TobbeEdgeware

**Comment by TobbeEdgeware** [comment]
Nja, jag kom vidare och satte upp allt jag behöver utan Lasses hjälp. Tror fortfarande att det kunde vara bra att dela upp dokumentationen och lägga till en del av det jag skrev ovan. Vet inte riktigt bästa sättet för att göra det. Det går ju att göra en PR mot README.md men då är det fortfarande den stora monolitiska filen. Wikin blir ett eget repo om man drar igång den om jag minns rätt.

**Comment by webbmastern** [comment]
Hej,
Jag tror jag lyckats få in det mesta in i en wiki [här](https://github.com/Scouterna/Google-Scoutnet-synk/wiki) så jag stänger denna issue.
