### ISSUE TITLE
Sätta recoveryPhone fungerar inte

### ISSUE THREAD

**Issue by stalar** [Scouterna/Google-Scoutnet-synk#31]
I korthet: för att sätta recoverPhone kräver Google att numret är på formatet E.164. intphonenumber() försöker nog skapa sådana telefonnummer men lyckas inte alltid varpå uppdateringen av användaren inte lyckas.

Ett exempel på ett telefonnummer som inte är rätt "46 70 7560000" (jag har skrivit nollor på slutet istf det riktiga numret).

Antingen bör recoveryPhone inte sättas (om man inte kan garantera rätt format) eller så kan man prova att sätta recoveryPhone i ett eget anrop så att inga andra uppdateringar av användaren försvinner pga detta problem.

**Comment by los7702** [comment]
Absolut skall inte funktionen kvadda uppdateringen. 
Jag tittar på detta denna veckan
