### ISSUE TITLE
Felaktig uppdatering av namn

### ISSUE THREAD

**Issue by kmjonsson** [Scouterna/Google-Scoutnet-synk#47]
Om en person byter namn i Scoutnet så blir uppdateringen felaktig.

rad 436 i Anvandare.gs ska vara:
  user.name.familyName = member.last_name;
inte
  user.name.givetName = ...

**Comment by kmjonsson** [comment]
Verkar vara en bug som fanns i 1.8 men lagat i 2.0 men instruktionerna säger inte att Anvander.gs ska uppdateras.

**Comment by los7702** [comment]
Lagad med #45 men utan versionsbyte
Ärendet kanske kan stängas?

**Comment by kmjonsson** [comment]
Dokumentationen för uppdatering från 1.8 till 2.0 är fortfarande felaktig.

**Comment by webbmastern** [comment]
Hej,
Då 2.0 var en viktig och brådskande uppdatering som jag ville skulle gå snabbt att uppdatera till kände jag att det enklaste skulle vara om användarna bara behövde uppdatera en fil så att detta inte skulle skjutas upp.
Då buggfixen redan var införd i utv-grenen så fick den följa med och jag drog då en liten fuling att inte nämna den fixen för att koden enbart skulle behöva uppdateras på ett ställe. Jag hade tänkt nämna den vid nästa version och ärendet kanske kan stängas då?

**Comment by kmjonsson** [comment]
Blir bra!
