### ISSUE TITLE
Skapa ett bibliotek av skripten

### ISSUE THREAD

**Issue by Johan-Havenberg** [Scouterna/Google-Scoutnet-synk#50]
Migrerade just till version 2.0, från 1.7 via 1.8.

Pallade ärligt talat inte flytta alla scriptfiler in i kalkylarket, men det behövde jag inte då jag kunde dra in alla scriptfilerna som ett bibliotek och enkelt skapa en lokal skriptfil som bara innehåller det jag vill köra.

Så nu har jag alla Scoutnet Sync skripten i ett projekt och exponerar det som ett bibliotek, drar in detta i kalkylarket där jag skapat en enda fil 'Mina_funktioner.gs' där jag exponerar de funktioner jag vill köra på timer.
![image](https://user-images.githubusercontent.com/89695491/132942305-545597f6-52db-4f05-8d2d-eca526609e46.png)

Min tanke var nu att det skulle vara sjukt nice om man istället för att kopiera scripten kunde dra in dem som ett bibliotek, då behöver alla inställningar flyttas ut ur biblioteket (Konfiguration.gs) kanske som ett settingsobjekt som sedan kunde skickas med vid körningar, på så sätt kunde jag som konsument enkelt välja vilken version av scripten jag ville köra med minimal insatts. Allt jag behöver är ett Script Id för att dra in scriptet.
Kanske funkar detta inte mellan google domäner, kanske är det förknippat med sjuka säkerhetsproblem, men jag villa bara så ett frö som skulle kunna underlätta för alla.

**Comment by los7702** [comment]
Nu är jag ute på hal is, men diskuterar gärna
Bibliotek/library är jättebra idé under förutsättning att man inte skall pilla i koden = rätt för de flesta kanske.
Då kan man möjligtvis få till så att man inte ens behöver uppdatera själv... 
Och och andra kan strunta i biblioteken/library och lägga in scriptfilerna manuellt. 
Spännande idé.

**Comment by webbmastern** [comment]
Hej,
Jag funderade en del på bibliotek när det fanns en version där det inte gick att dela upp körningen av olika grupper så att alla grupper synkas samtidigt. Detta då det ibland tog slut på tid för körningen och då dokumentationen säger att det tar längre tid med bibliotek än utan och kände då i allafall att det inte var en lämplig lösning. https://developers.google.com/apps-script/guides/libraries

Bland kårerna blir det enklare att uppdatera men jag känner att det förutom att utreda ev prestandaproblem också behöver funderas på en del säkerhetsfrågor.

Jag är positiv till idén och tror att den kommer införas, men antagligen inte till nästa version då det kommer massor av ny kod och att det är bra om det blir uppdelat.
