### ISSUE TITLE
Etiketter för val av synkronisering av Grupper

### ISSUE THREAD

**Issue by Johan-Havenberg** [Scouterna/Google-Scoutnet-synk#51]
I enlighet med rekommendationen, kör jag raderna i grupper som olika triggers för att det inte ska ta för lång tid.

Det skulle vara trevligt om man kunde välja rader baserat på tex en tag (ny kolumn) så att man slapp uppdatera på två eller fler ställen när man lägger in en rad  i kalkylarket.

Jag har valt att köra rader som motsvarar olika grupperingar, och att sätta en tag på de raderna och att kunna välja ut rader för körning baserat på den hade varit guld.

T.ex.
I kalkylarket har jag ett antal rader som rör kårens avdelningar. Jag har valt att köra alla avdelningar i en batch och kallar den funktionen `Grupper_Avdelningar` 
```js
function Grupper_Avdelningar() {
  Grupper(17, 29);
}
```

Problemet är nu att urvalet baserar sig på radnummer och om jag tar bort, infogar, eller lägger till rader i kalkylarket, måste jag uppdatera skriptet. Skulle vara sjukt bra om man istället kunde köra grupper typ så här:
```js
function Grupper_Avdelningar() {
  var rader = HamtaGruppRaderForTag("Avdelningar")
  Grupper(rader);
}
```

**Comment by webbmastern** [comment]
Låter som en bra idé. Jag fixar det till en kommande version.

**Comment by webbmastern** [comment]
I nästa version så kommer det gå att göra olika anrop till Grupper() med radnummer och etiketter. T.ex

```
function GrupperVissaRader1() {
  Grupper(0, 10);
}
```

```
function GrupperVissaRaderOchEtikett1() {
  Grupper(0, 10, "Avdelningar");
}
```

```
function GrupperVissEtikett1() {
  Grupper("Avdelningar");
}
```
