### ISSUE TITLE
Google grupps

### ISSUE THREAD

**Issue by mrab95** [Scouterna/Google-Scoutnet-synk#55]
is:issue is:open vi har Google grupper som vi vill bara organisationen ska kunna skicka till så jag gjorde dom inställningarna i mitt  kalkylark. Med @ i "Kan skicka" men detta gorde också att andra grupper inte kan skicka till den utan bara använder. Har jag gjort fel eller är detta något som går att lösa?

**Comment by webbmastern** [comment]
Hej,
Om du enbart vill att några ska kunna skicka till en lista kan du börja med att fylla i vilka som ska vara mottagarna genom att fylla i  **Kan ta emot//Scoutnet-id** samt **Kan ta emot//Synkinställning**.

Du fyller sen i under **Kan skicka//Scoutnet-id** ett **@** om du vill att enbart kårens Google-konton ska kunna skicka till listan. Om du vill att enbart kårens ledare oavsett kårkonto hos Google eller deras privata mejl eller något ska gå att skickas från t.ex. skapar du en lämplig e-postlista i Scoutnet och fyller i detta list-id under **Kan skicka//Scoutnet-id**. Under **Kan skicka//synkinställning** väljer du vilka e-postadresskällor för dessa ledare som ska gå att skicka från. T.ex primär e-post, anhörig e-post.
