### ISSUE TITLE
Ändra "reply-to" inställningen för en maillista

### ISSUE THREAD

**Issue by hakankvist** [Scouterna/Google-Scoutnet-synk#8]
Svarar man på ett mail som kommer till en lista, så svarar man alltid till listan.
Det går inte att ändra fältet för to-mailadressen i gmail (det fältet verkar helt låst).

Det hade varit najs om man kunde ändra den inställningen i kalkylarket, ändrar jag inställningen manuellt i grupper så verkar den skrivas över vid nästa synk.

**Comment by webbmastern** [comment]
När du ändrar inställningen manuellt.
Vad är den inställd på innan och vad försöker du ändra den till.
Uppfattar jag det rätt med att du vill ändra så att man svarar avsändaren istället för listan?
Jag tror det blir för många kolumner om man ska kunna ställa in detta i kalkylarket, så det bästa skulle nog vara en generell lösning.

**Comment by hakankvist** [comment]
Jag tror vi kan stänga den här issuen.
Jag måste ha tänkt att jag ska svara sen och sen missat att svara.

Felet var att när jag tryckte reply på ett mail som skickats till en lista, så kunde jag inte ändra i fältet där jag skulle ange addressater i gmail, utan det fältet var låst.
Jag misstänkte då att de kunde ha att göra med inställningarna för listorna var uppsatta.

Försökte hitta en lista nu där jag kunde reproducera felet men har inte lyckats, så jag tror vi kan stänga den här felrapporten.
