### ISSUE TITLE
Medlemslistor - dokument bifogas ej.

### ISSUE THREAD

**Issue by fredrikbaberg** [Scouterna/Google-Scoutnet-synk#82]
Jag har en fungerande testmedlemslista men har problem att få bifogat dokument att fungera, möts av följande felmeddelande när jag anropar `synkroniseraMedlemslistorVissaRaderUppdateraOchSkicka1`: `[TypeError: Cannot read properties of null (reading 'getText')]`. Mejlet går iväg, men det finns ingen bifogad PDF.

Jag har skapat ett Google Dokument med lite text i för att testa, typ `Hej {{Förnamn}} {{Efternamn}}`, och kopierat dokumentets ID till kolumn F ("Koppla dokument").

Antagligen uppstår felet på https://github.com/Scouterna/Google-Scoutnet-synk/blob/8762803ce7d9373fafce34762a5cf72462109cbd/Bibliotek/Medlemslistor-lib.gs#L649. Observera att jag kör versionen vi diskuterade i samband med #81.

**Comment by webbmastern** [comment]
@fredrikbaberg Jag har uppdaterat testbiblioteket om du vill testa. Välj senaste versionen.

**Comment by fredrikbaberg** [comment]
Tack, nu fick jag en PDF bifogad.
