### ISSUE TITLE
Öka användarvänlighet för synk av kontakter?

### ISSUE THREAD

**Issue by fredrikbaberg** [Scouterna/Google-Scoutnet-synk#83]
Jag har testat lite med att synka kontakter men är lite osäker på användarvänligheten. Har jag förstått det rätt är nuvarande lösning att inom kåren dela ett kalkylark där användaren skriver in sin e-postadress och lösenord (eller lämnar lösenord blankt för att få det skickat till sig), trycker på en knapp, så ska synkronisering aktiveras.

Det jag funderar på är:
* När användaren skriver in sina uppgifter kommer det loggas i historiken för dokumentet, vilket kan vara olämpligt.
* Fler användare kan inte fylla i det samtidigt.
* Är det lämpligt/nödvändigt att alla får tillgång till länk till webbapp/webbadress och möjlighet att redigera avancerade fält?

Kalkylarket ska visserligen bara delas inom kåren, och lösenordet ger en begränsad åtkomst, men det är kanske ändå bra att hålla nere risken att något går fel.

Ett alternativ skulle vara att ersätta kalkylarket som delas med ett formulär. Parametrarna kan antingen sättas i ett skript, eller så används funktionen med förifyllda data. Det är något jag börjat kolla på, men kommer behöva skriva om delar av `Kontakter-Anvandare.gs` för att det ska fungera.
Jag ser egentligen två nackdelar:
* Formulär är inte avsedda för att skicka in lösenord.
* Menyn "Scoutnet" i kalkylarket går inte att lägga till (är det något användaren ska komma åt?).

Annars kanske det går att använda Google Sites? Vet inte om det är lika enkelt att dela mellan kårer.

**Comment by fredrikbaberg** [comment]
Efter att ha testat en del med formulär inser jag att det antagligen inte kommer fungera, på grund av behörigheter.
Med kalkylarket kommer en fråga om att ge skriptet behörigheter för att köras, det gör det inte genom formulär, så skriptet körs som fel användare.

**Comment by webbmastern** [comment]
Hej,
Min tanke var att kårens funktionärer ska kopiera kalkylarksmallen så att de får ett eget kalkylark som då kommer hålla deras e-postadress/lösenord för synkronisering samt skript och när skriptet ska köras.
Jag såg att det inte framgick i wikin, så jag har nu uppdaterat det under [kapitel 4](https://github.com/Scouterna/Google-Scoutnet-synk/wiki/Manual-Kontakter#st%C3%A4lla-in-synkronisering-av-kontaktgrupper) för manualen för Kontakter.
Jag la också till tipset att endast ge läsbehörighet för filen till kårens funktionärer så att de inte råkar fylla i något.

Ang vilka inställningar som en vanligt kåranvändare ska kunna pilla på tror jag är svårt att få en helt enhetlig syn på, men någonstans måste adressen till webbappen finnas. Antingen i kalkylarket eller i koden. Om man inte vill att den ska synas är nog det enklaste att dölja den raden innan man skickar vidare länken.
